import 'package:get/get.dart';

import '../models/district_block_model.dart';

class RegistrationController extends GetxController{

  var selectedDistrict = ''.obs;
  var selectedBlock = ''.obs;

  final List<DistrictBlockModel> districts = [
    DistrictBlockModel(
      name: "Alipurduar",
      blocks: [
        "Alipurduar-I",
        "Alipurduar-II",
        "Falakata",
        "Kalchini",
        "Kumargram",
        "Madarihat"
      ],
    ),
    DistrictBlockModel(
      name: "Bankura",
      blocks: [
        "Bankura-I",
        "Bankura-II",
        "Barjora",
        "Chhatna",
        "Gangajal Ghati",
        "Hirbandh",
        "Indpur",
        "Indus",
        "Jaypur",
        "Khatra-I",
        "Kotulpur",
        "Mejhia",
        "Onda",
        "Patrasayer",
        "Raipur-I",
        "Ranibundh",
        "Saltora",
        "Sarenga",
        "Simlapal",
        "Sonamukhi",
        "Taldangra",
        "Vishnupur"
      ],
    ),
    DistrictBlockModel(
      name: "Birbhum",
      blocks: [
        "Bolpur-Sriniketan",
        "Dubrajpur",
        "Illambazar",
        "Khoyrasol",
        "Labpur",
        "Mayureswar-I",
        "Mayureswar-II",
        "Mohammad Bazar",
        "Murarai-I",
        "Murarai-II",
        "Nalhati-I",
        "Nalhati-II",
        "Nanoor",
        "Rajnagar",
        "Rampurhat-I",
        "Rampurhat-II",
        "Sainthia",
        "Suri-I",
        "Suri-II"
      ],
    ),
    DistrictBlockModel(
      name: "Cooch Behar",
      blocks: [
        "Cooch Behar II",
        "Cooch Behar I",
        "Dinhata-I",
        "Dinhata-II",
        "Haldibari",
        "Mathabhanga II",
        "Mathabhanga-I",
        "Mekliganj",
        "Sitai",
        "Sitalkuchi",
        "Tufanganj-I",
        "Tufanganj-II"
      ],
    ),
    DistrictBlockModel(
      name: "Dakshin Dinajpur",
      blocks: [
        "Balurghat",
        "Bansihari",
        "Gangarampur",
        "Harirampur",
        "Hili",
        "Kumarganj",
        "Kushmandi",
        "Tapan"
      ],
    ),
    DistrictBlockModel(
      name: "Darjeeling",
      blocks: [
        "Darjeeling-Pulbazar",
        "Jore Bunglow-Sukiapokhri",
        "Kharibari",
        "Kurseong",
        "Matigara",
        "Mirik",
        "Naxal Bari",
        "Phansidewa",
        "Rangli Rangliot"
      ],
    ),
    DistrictBlockModel(
      name: "Hooghly",
      blocks: [
        "Arambagh",
        "Balagarh",
        "Chanditala-I",
        "Chanditala-II",
        "Chinsurah-Magrah",
        "Dhaniakhali",
        "Goghat-I",
        "Goghat-II",
        "Haripal",
        "Jangipara",
        "Khanakul-I",
        "Khanakul-II",
        "Pandua",
        "Polba-Dadpur",
        "Pursurah",
        "Singur",
        "Sirampur-Uttarpara",
        "Tarakeswar"
      ],
    ),
    DistrictBlockModel(
      name: "Howrah",
      blocks: [
        "Amta-I",
        "Amta-II",
        "Bagnan-I",
        "Bagnan-II",
        "Bally-Jagacha",
        "Domjur",
        "Jagatballavpur",
        "Panchla",
        "Sankrail",
        "Shyampur-I",
        "Shyampur-II",
        "Udaynarayanpur",
        "Uluberia-I",
        "Uluberia-II"
      ],
    ),
    DistrictBlockModel(
      name: "Jalpaiguri",
      blocks: [
        "Banarhat",
        "Dhupguri",
        "Jalpaiguri",
        "Kranti",
        "Mal",
        "Matiali",
        "Maynaguri",
        "Nagrakata",
        "Rajganj"
      ],
    ),
    DistrictBlockModel(
      name: "Jhargram",
      blocks: [
        "Binpur-I",
        "Binpur-II",
        "Gopiballav Pur-II",
        "Gopiballavpur-I",
        "Jambani",
        "Jhargram",
        "Nayagram",
        "Sankrail"
      ],
    ),
    DistrictBlockModel(
      name: "Kalimpong",
      blocks: [
        "Gorubathan",
        "Kalimpong-I",
        "Lava",
        "Pedong"
      ],
    ),
    DistrictBlockModel(
      name: "Malda",
      blocks: [
        "Bamongola",
        "Chanchal-I",
        "Chanchal-II",
        "English Bazar",
        "Gazole",
        "Habibpur",
        "Harishchandrapur-I",
        "Harishchandrapur-II",
        "Kaliachak-I",
        "Kaliachak-II",
        "Kaliachak-III",
        "Manikchak",
        "Old Malda",
        "Ratua-I",
        "Ratua-II"
      ],
    ),
    DistrictBlockModel(
      name: "Murshidabad",
      blocks: [
        "Beldanga-I",
        "Beldanga-II",
        "Berhampore",
        "Bhagabangola-II",
        "Bhagawangola-I",
        "Bharatpur-I",
        "Bharatpur-II",
        "Burwan",
        "Domkal",
        "Farakka",
        "Hariharpara",
        "Jalangi",
        "Kandi",
        "Khargram",
        "Lalgola",
        "Murshidabad-Jiagunj",
        "Nabagram",
        "Nawda",
        "Raghunathganj-I",
        "Raghunathganj-II",
        "Raninagar-I",
        "Raninagar-II",
        "Sagardighi",
        "Shamsherganj",
        "Suti-I",
        "Suti-II"
      ],
    ),
    DistrictBlockModel(
      name: "Nadia",
      blocks: [
        "Chakdah",
        "Chapra",
        "Hanskhali",
        "Haringhata",
        "Kaliganj",
        "Kalyani",
        "Karimpur-1",
        "Karimpur-Ii",
        "Krishnaganj",
        "Krishnagar-I",
        "Krishnagar-Ii",
        "Nabadwip",
        "Nakashipara",
        "Ranaghat-I",
        "Ranaghat-Ii",
        "Santipur",
        "Tehatta-I",
        "Tehatta-Ii"
      ],
    ),
    DistrictBlockModel(
      name: "North 24 Parganas",
      blocks: [
        "Amdanga",
        "Baduria",
        "Bagda",
        "Barasat-I",
        "Barasat-II",
        "Barrackpur-I",
        "Barrackpur-II",
        "Basirhat-I",
        "Basirhat-II",
        "Bongaon",
        "Deganga",
        "Gaighata",
        "Habra-I",
        "Habra-II",
        "Haroa",
        "Hasnabad",
        "Hingalganj",
        "Minakhan",
        "Rajarhat",
        "Sandeshkhali-I",
        "Sandeshkhali-II",
        "Swarupnagar"
      ],
    ),
    DistrictBlockModel(
      name: "Paschim Bardhaman",
      blocks: [
        "Barabani",
        "Faridpur - Durgapur",
        "Jamuria",
        "Kanksa",
        "Ondal",
        "Pandabeswar",
        "Raniganj",
        "Salanpur"
      ],
    ),
    DistrictBlockModel(
      name: "Paschim Medinipur",
      blocks: [
        "Chandrakona-I",
        "Chandrakona-II",
        "Dantan-I",
        "Dantan-II",
        "Daspur-I",
        "Daspur-II",
        "Debra",
        "Garbeta-I",
        "Garbeta-II",
        "Garbeta-III",
        "Ghatal",
        "Keshiary",
        "Keshpur",
        "Kharagpur-I",
        "Kharagpur-II",
        "Midnapore",
        "Mohanpur",
        "Narayangarh",
        "Pingla",
        "Sabang",
        "Salbani"
      ],
    ),
    DistrictBlockModel(
      name: "Purba Bardhaman",
      blocks: [
        "Ausgram-I",
        "Ausgram-II",
        "Bhatar",
        "Burdwan-I",
        "Burdwan-II",
        "Galsi -I",
        "Galsi-Ii",
        "Jamal Pur",
        "Kalna II",
        "Kalna-I",
        "Katwa-I",
        "Katwa-Ii",
        "Ketugram-Ii",
        "Ketugram_I",
        "Khandaghosh",
        "Mangolkote",
        "Manteswar",
        "Memari-1",
        "Memari-Ii",
        "Purbasthali-I",
        "Purbasthali-Ii",
        "Raina-I",
        "Raina-Ii"
      ],
    ),
    DistrictBlockModel(
      name: "Purba Medinipur",
      blocks: [
        "Bhagawanpur-I",
        "Bhagawanpur-Ii",
        "Chandipur",
        "Contai-I",
        "Contai-Iii",
        "Deshapran",
        "Egra-I",
        "Egra-Ii",
        "Haldia",
        "Khejuri-I",
        "Khejuri-Ii",
        "Kolaghat",
        "Mahishadal",
        "Moyna",
        "Nandakumar",
        "Nandigram-I",
        "Nandigram-Ii",
        "Panskura-I",
        "Patashpur-I",
        "Patashpur-Ii",
        "Ramnagar-I",
        "Ramnagar-Ii",
        "Shahid Matangini",
        "Sutahata",
        "Tamluk"
      ],
    ),
    DistrictBlockModel(
      name: "Purulia",
      blocks: [
        "Arsha",
        "Bagmundi",
        "Balarampur",
        "Barabazar",
        "Bundwan",
        "Hura",
        "Jaipur",
        "Jhalda-I",
        "Jhalda-Ii",
        "Kashipur",
        "Manbazar-I",
        "Manbazar-Ii",
        "Neturia",
        "Para",
        "Puncha",
        "Purulia-I",
        "Purulia-Ii",
        "Raghunath Pur-I",
        "Raghunathpur-Ii",
        "Santuri"
      ],
    ),
    DistrictBlockModel(
      name: "South 24 Parganas",
      blocks: [
        "Baruipur",
        "Basanti",
        "Bhangar-I",
        "Bhangar-Ii",
        "Bishnupur-I",
        "Bishnupur-Ii",
        "Budge Budge-I",
        "Budge Budge-Ii",
        "Canning-I",
        "Canning-Ii",
        "Diamond Harbour-I",
        "Diamond Harbour-Ii",
        "Falta",
        "Gosaba",
        "Jaynagar-I",
        "Jaynagar-Ii",
        "Kak Dwip",
        "Kulpi",
        "Kultali",
        "Magra Hat-I",
        "Magra Hat-Ii",
        "Mandirbazar",
        "Mathurapur I",
        "Mathurapur-Ii",
        "Namkhana",
        "Pathar Pratima",
        "Sagar",
        "Sonarpur",
        "Thakurpukur Mahestola"
      ],
    ),
    DistrictBlockModel(
      name: "Uttar Dinajpur",
      blocks: [
        "Chopra",
        "Goalpokhar II",
        "Goalpokhar-I",
        "Hemtabad",
        "Islampur",
        "Itahar",
        "Kaliaganj",
        "Karandighi",
        "Raiganj"
      ],
    ),
  ];
}